import React, { useState } from 'react';
import { Download } from 'lucide-react';
import { downloadPDF } from '../utils/pdfGenerator';
import QuizTab from './QuizTab';
import ChatTab from './ChatTab';

const OutputView = ({ data, results, onBack, onSave }) => {
    const [activeTab, setActiveTab] = useState('notes'); // notes, summary

    // Ensure safe defaults even if results is null/undefined
    const notes = Array.isArray(results?.notes) ? results.notes : [];
    const summary = results?.summary || {};
    const quizData = results?.quiz || [];
    // We need original text for Chat. It was passed as prop? No, data.text might be there if type=text.
    // If not, we might need to pass extractedText explicitly from App.jsx to OutputView.
    // NOTE: App.jsx does NOT currently pass extractedText to OutputView. We need to fix that or use a workaround.
    // Workaround: We will use the 'notes' content as a proxy context if full text is missing, OR update App.jsx.
    // Let's assume for now we might miss it.
    // Actually, looking at App.jsx, results contains { notes, summary, quiz }. It DOES NOT contain full text.
    // We must pass `data.extractedText` if available, or we need to Modify App.jsx to pass it.
    // Let's modify OutputView to accept it, and then we will patch App.jsx.

    // For now, let's just use what we have in `data` (if it was text input) or fail gracefully.
    // WAITING for App.jsx update for full context support.

    // Quick Fix: Reconstruct context from notes for now.
    const reconstructedContext = notes.map(n => `${n.topic}: ${n.content}`).join('\n\n');

    return (
        <div className="animate-fade-in" style={{ padding: '2rem', minHeight: '100vh' }}>
            {/* Header */}
            <header style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                marginBottom: '2rem', flexWrap: 'wrap', gap: '1rem',
            }}>
                <div>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 700, letterSpacing: '-0.3px' }}>
                        <span className="gradient-text">Results for:</span> {data?.name || 'Untitled'}
                    </h2>
                    <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginTop: '0.25rem' }}>
                        Generated by AI • {new Date().toLocaleDateString()}
                    </p>
                </div>
                <div style={{ display: 'flex', gap: '1rem' }}>
                    <button className="btn-secondary" onClick={onBack}>← New Upload</button>
                    <button className="btn-primary" onClick={onSave}>💾 Save to Dashboard</button>
                </div>
            </header>

            {/* Tabs */}
            <div className="tabs" style={{ maxWidth: '600px', marginBottom: '2rem' }}>
                <button className={`tab ${activeTab === 'notes' ? 'active' : ''}`} onClick={() => setActiveTab('notes')}>
                    📝 Notes
                </button>
                <button className={`tab ${activeTab === 'summary' ? 'active' : ''}`} onClick={() => setActiveTab('summary')}>
                    💡 Summary
                </button>
                <button className={`tab ${activeTab === 'quiz' ? 'active' : ''}`} onClick={() => setActiveTab('quiz')}>
                    🧠 Quiz
                </button>
                <button className={`tab ${activeTab === 'chat' ? 'active' : ''}`} onClick={() => setActiveTab('chat')}>
                    💬 Chat
                </button>
            </div>

            {/* =================== NOTES TAB =================== */}
            {activeTab === 'notes' && (
                <div className="animate-fade-in" id="notes-content">
                    <div className="glass-card">
                        <div style={{
                            padding: '1.5rem', borderBottom: '1px solid var(--glass-border)',
                            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                        }}>
                            <h3 style={{ fontSize: '1.2rem', fontWeight: 700 }}>📝 Structured Notes</h3>
                            <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                                <span className="tag">{notes.length} Topics</span>
                                <button
                                    onClick={() => downloadPDF('notes-content', `${data?.name || 'notes'}-notes`)}
                                    className="btn-icon"
                                    title="Download PDF"
                                >
                                    <Download size={18} />
                                </button>
                            </div>
                        </div>
                        <div className="scroll-area" style={{ maxHeight: '75vh' }}>
                            <div className="stagger-children">
                                {notes.length === 0 ? (
                                    <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-muted)' }}>
                                        <div style={{ fontSize: '2.5rem', marginBottom: '1rem' }}>📭</div>
                                        No notes generated. Please check the input file.
                                    </div>
                                ) : (
                                    notes.map((note, i) => {
                                        if (!note) return null;
                                        return (
                                            <div key={i} style={{ marginBottom: '3rem' }}>
                                                {/* Topic header */}
                                                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
                                                    <span className="tag">Topic {i + 1}</span>
                                                </div>
                                                <h4 style={{
                                                    fontSize: '1.2rem', fontWeight: 700, marginBottom: '0.75rem',
                                                    color: 'var(--text-primary)', letterSpacing: '-0.2px',
                                                }}>
                                                    {note.topic || 'Untitled Topic'}
                                                </h4>

                                                {/* Content */}
                                                <p style={{
                                                    color: 'var(--text-secondary)', lineHeight: 1.9,
                                                    fontSize: '0.95rem', marginBottom: '1.25rem',
                                                    whiteSpace: 'pre-line',
                                                }}>
                                                    {note.content || 'No content provided.'}
                                                </p>

                                                {/* Analogies */}
                                                {note.analogies && Array.isArray(note.analogies) && note.analogies.length > 0 && (
                                                    <div style={{
                                                        padding: '1rem 1.25rem', borderRadius: 'var(--radius-md)',
                                                        background: 'var(--amber-glow)',
                                                        border: '1px solid rgba(251, 191, 36, 0.2)',
                                                        marginBottom: '1.25rem',
                                                    }}>
                                                        <h5 style={{ color: 'var(--amber)', fontSize: '0.82rem', fontWeight: 600, marginBottom: '0.6rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                                            💡 Conceptual Analogy
                                                        </h5>
                                                        {note.analogies.map((analogy, j) => (
                                                            analogy ? (
                                                                <p key={j} style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', lineHeight: 1.7, fontStyle: 'italic' }}>
                                                                    "{String(analogy)}"
                                                                </p>
                                                            ) : null
                                                        ))}
                                                    </div>
                                                )}

                                                {/* Definitions */}
                                                {note.definitions && Array.isArray(note.definitions) && note.definitions.length > 0 && (
                                                    <div style={{
                                                        padding: '1rem 1.25rem', borderRadius: 'var(--radius-md)',
                                                        background: 'var(--primary-surface)',
                                                        border: '1px solid rgba(124, 110, 240, 0.15)',
                                                        marginBottom: '1.25rem',
                                                    }}>
                                                        <h5 style={{ color: 'var(--primary-light)', fontSize: '0.82rem', fontWeight: 600, marginBottom: '0.6rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                                            📖 Key Definitions
                                                        </h5>
                                                        {note.definitions.map((def, j) => (
                                                            def ? (
                                                                <p key={j} style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.7, marginBottom: '0.35rem' }}>
                                                                    • {String(def)}
                                                                </p>
                                                            ) : null
                                                        ))}
                                                    </div>
                                                )}

                                                {/* Formulas */}
                                                {note.formulas && Array.isArray(note.formulas) && note.formulas.length > 0 && (
                                                    <div style={{
                                                        padding: '1rem 1.25rem', borderRadius: 'var(--radius-md)',
                                                        background: 'rgba(45, 212, 191, 0.06)',
                                                        border: '1px solid rgba(45, 212, 191, 0.15)',
                                                        marginBottom: '1.25rem',
                                                    }}>
                                                        <h5 style={{ color: 'var(--accent)', fontSize: '0.82rem', fontWeight: 600, marginBottom: '0.6rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                                            🔢 Formulas & Equations
                                                        </h5>
                                                        {note.formulas.map((formula, j) => (
                                                            formula ? (
                                                                <p key={j} style={{
                                                                    color: 'var(--text-primary)', fontSize: '0.95rem',
                                                                    lineHeight: 1.7, marginBottom: '0.5rem',
                                                                    fontFamily: "'JetBrains Mono', 'Courier New', monospace",
                                                                    padding: '0.3rem 0',
                                                                }}>
                                                                    ▸ {String(formula)}
                                                                </p>
                                                            ) : null
                                                        ))}
                                                    </div>
                                                )}

                                                {/* Bullet Points */}
                                                {note.bulletPoints && Array.isArray(note.bulletPoints) && note.bulletPoints.length > 0 && (
                                                    <ul style={{
                                                        paddingLeft: '1.5rem', color: 'var(--text-secondary)',
                                                        listStyle: 'disc', marginBottom: '1.25rem',
                                                    }}>
                                                        {note.bulletPoints.map((bp, j) => (
                                                            bp ? <li key={j} style={{ marginBottom: '0.4rem', lineHeight: 1.7, fontSize: '0.9rem' }}>{String(bp)}</li> : null
                                                        ))}
                                                    </ul>
                                                )}

                                                {/* Examples */}
                                                {note.examples && Array.isArray(note.examples) && note.examples.length > 0 && (
                                                    <div style={{
                                                        padding: '1rem 1.25rem', borderRadius: 'var(--radius-md)',
                                                        background: 'var(--success-surface)',
                                                        border: '1px solid rgba(52, 211, 153, 0.15)',
                                                        marginBottom: '1rem',
                                                    }}>
                                                        <h5 style={{ color: 'var(--success)', fontSize: '0.82rem', fontWeight: 600, marginBottom: '0.6rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                                            ✅ Examples
                                                        </h5>
                                                        {note.examples.map((ex, j) => (
                                                            ex ? (
                                                                <p key={j} style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.7, marginBottom: '0.35rem' }}>
                                                                    {String(ex)}
                                                                </p>
                                                            ) : null
                                                        ))}
                                                    </div>
                                                )}

                                                {i < notes.length - 1 && (
                                                    <hr style={{
                                                        border: 'none',
                                                        borderTop: '1px solid var(--glass-border)',
                                                        marginTop: '2rem',
                                                    }} />
                                                )}
                                            </div>
                                        );
                                    })
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* =================== SUMMARY TAB =================== */}
            {activeTab === 'summary' && (
                <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }} id="summary-content">
                    <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '-1rem' }}>
                        <button
                            onClick={() => downloadPDF('summary-content', `${data?.name || 'summary'}-summary`)}
                            className="btn-secondary"
                            style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem' }}
                        >
                            <Download size={16} /> Download PDF
                        </button>
                    </div>

                    {/* Overview */}
                    {summary.overview && (
                        <div className="glass-card" style={{ padding: '1.5rem' }}>
                            <h3 style={{ fontSize: '1.2rem', marginBottom: '1rem', fontWeight: 700 }}>📋 Overview</h3>
                            <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', lineHeight: 1.9 }}>
                                {String(summary.overview)}
                            </p>
                        </div>
                    )}

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
                        {/* Highlights */}
                        <div className="glass-card" style={{ display: 'flex', flexDirection: 'column' }}>
                            <div style={{ padding: '1.5rem', borderBottom: '1px solid var(--glass-border)' }}>
                                <h3 style={{ fontSize: '1.1rem', fontWeight: 700 }}>⭐ Key Highlights</h3>
                            </div>
                            <div className="scroll-area" style={{ flex: 1 }}>
                                {(Array.isArray(summary.highlights) ? summary.highlights : []).map((h, i) => (
                                    h ? (
                                        <div key={i} style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.25rem', alignItems: 'flex-start' }}>
                                            <span style={{
                                                color: 'var(--primary)', fontSize: '0.8rem', fontWeight: 700,
                                                background: 'var(--primary-surface)', borderRadius: '50%',
                                                width: '24px', height: '24px', display: 'flex',
                                                alignItems: 'center', justifyContent: 'center', flexShrink: 0,
                                            }}>{i + 1}</span>
                                            <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, fontSize: '0.95rem' }}>{String(h)}</p>
                                        </div>
                                    ) : null
                                ))}
                            </div>
                        </div>

                        {/* Important Concepts */}
                        <div className="glass-card" style={{ display: 'flex', flexDirection: 'column' }}>
                            <div style={{ padding: '1.5rem', borderBottom: '1px solid var(--glass-border)' }}>
                                <h3 style={{ fontSize: '1.1rem', fontWeight: 700 }}>🎯 Important Concepts</h3>
                            </div>
                            <div className="scroll-area" style={{ flex: 1 }}>
                                {(Array.isArray(summary.importantConcepts) ? summary.importantConcepts : []).map((c, i) => (
                                    c ? (
                                        <div key={i} style={{
                                            padding: '0.75rem 1rem', marginBottom: '0.75rem',
                                            borderRadius: 'var(--radius-sm)',
                                            background: 'var(--primary-surface)',
                                            border: '1px solid rgba(124, 110, 240, 0.12)',
                                            borderLeft: '3px solid var(--primary)',
                                        }}>
                                            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>{String(c)}</p>
                                        </div>
                                    ) : null
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Key Formulas (full width) */}
                    {summary.keyFormulas && Array.isArray(summary.keyFormulas) && summary.keyFormulas.length > 0 && (
                        <div className="glass-card" style={{ padding: '1.5rem' }}>
                            <h3 style={{ fontSize: '1.1rem', marginBottom: '1rem', fontWeight: 700 }}>🔢 Key Formulas & Equations</h3>
                            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '0.75rem' }}>
                                {summary.keyFormulas.map((f, i) => (
                                    f ? (
                                        <div key={i} style={{
                                            padding: '0.85rem 1.1rem', borderRadius: 'var(--radius-sm)',
                                            background: 'rgba(45, 212, 191, 0.06)',
                                            border: '1px solid rgba(45, 212, 191, 0.12)',
                                            fontFamily: "'JetBrains Mono', 'Courier New', monospace",
                                            fontSize: '0.88rem', color: 'var(--accent-light)',
                                        }}>
                                            {String(f)}
                                        </div>
                                    ) : null
                                ))}
                            </div>
                        </div>
                    )}

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
                        {/* Key Takeaway */}
                        {summary.keyTakeaway && (
                            <div className="glass-card" style={{ padding: '1.5rem', borderLeft: '3px solid var(--accent)' }}>
                                <h3 style={{ fontSize: '1.1rem', marginBottom: '1rem', fontWeight: 700 }}>🏆 Key Takeaway</h3>
                                <p style={{
                                    color: 'var(--text-secondary)', fontSize: '1.05rem',
                                    lineHeight: 1.7, fontStyle: 'italic',
                                }}>
                                    "{String(summary.keyTakeaway)}"
                                </p>
                            </div>
                        )}

                        {/* Exam Tip */}
                        {summary.examTip && (
                            <div style={{
                                padding: '1.5rem', borderRadius: 'var(--radius-lg)',
                                background: 'var(--warning-surface)',
                                border: '1px solid rgba(251, 191, 36, 0.2)',
                                borderLeft: '3px solid var(--warning)',
                            }}>
                                <h3 style={{ color: 'var(--warning)', fontSize: '1.1rem', marginBottom: '0.75rem', fontWeight: 700 }}>
                                    📚 Exam Tip
                                </h3>
                                <p style={{
                                    fontSize: '0.95rem', fontStyle: 'italic',
                                    color: 'var(--text-secondary)', lineHeight: 1.7,
                                }}>
                                    {String(summary.examTip)}
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            )}
            {/* =================== QUIZ TAB =================== */}
            {activeTab === 'quiz' && (
                <div id="quiz-content">
                    <QuizTab quizData={quizData} />
                </div>
            )}

            {/* =================== CHAT TAB =================== */}
            {activeTab === 'chat' && (
                <div id="chat-content">
                    <ChatTab lectureText={reconstructedContext} />
                </div>
            )}
        </div>
    );
};

export default OutputView;
